CREATE USER Dirigente IDENTIFIED BY DirigenteNegozio;
CREATE USER Tecnico IDENTIFIED BY TecnicoDB;
CREATE USER Cassiere IDENTIFIED BY CassiereNegozio;
CREATE USER Magazziniere IDENTIFIED BY MagazziniereNegozio;

-- PERMESSI PER IL DIRIGENTE
GRANT ALL PRIVILEGES TO Dirigente;

-- PERMESSI PER L'ESECUZIONE DELLE PROCEDURE
GRANT EXECUTE ON ApplicazioneOfferta TO Cassiere;
GRANT EXECUTE ON VenditaProdotti TO Magazziniere;
GRANT EXECUTE ON CassierePiuProduttivo TO Tecnico;
GRANT EXECUTE ON OffertaMenoVenduto TO Cassiere;

-- PERMESSI PER IL TECNICO
GRANT SELECT, INSERT, UPDATE ON Credenziali TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Dipendente TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Contratto TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Stipendio TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Presenza TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Ferie TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Cassa TO Tecnico;
GRANT SELECT ON Brand TO Tecnico;
GRANT SELECT, INSERT, UPDATE ON Offerta TO Tecnico;

-- PERMESSI PER IL CASSIERE
GRANT SELECT ON Scontrino TO Cassiere;

-- PERMESSI PER IL MAGAZZINIERE
GRANT SELECT, INSERT, UPDATE ON Prodotto TO Magazziniere;
GRANT SELECT, INSERT, UPDATE ON Videogioco TO Magazziniere;
GRANT SELECT, INSERT, UPDATE ON Console TO Magazziniere;
GRANT SELECT, INSERT, UPDATE ON Accessorio TO Magazziniere;